SDKError: add tests for toString
Needed to hack around this a bit, since Jest + Coverage doesn’t really
work well when we inherit from basic types like Error/Array etc.. Should
get better when Babel7 is released, apparently, but whatevs — working
around it.