SDKError: add unit test for toString
This actually onmasked a jest config issue (Jest uses babel under the
hood, and that prevents tests from inheriting core types such as Error.

Since we’re doing this, I saw that .toString() didn’t do anything at
all, and was a bit puzzled why.. But mystery solved..